# This file should be encrypted using: ansible-vault encrypt ansible/vars/secrets.yml
# Use the password defined in .vault_pass

vault_mongodb_uri: "mongodb://mongodb:27017/scholar-study"
vault_jwt_secret: "scholar_secret_123_change_me"
vault_groq_api_key: "gsk_..." # Your actual Groq API Key
vault_docker_hub_token: "..."
